//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroInstall.Publish.Cli.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeroInstall.Publish.Cli.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feed file '{0}' does not exist. Create it?.
        /// </summary>
        internal static string AskCreateFeed {
            get {
                return ResourceManager.GetString("AskCreateFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the GnuPG passphrase for {0}:.
        /// </summary>
        internal static string AskForPassphrase {
            get {
                return ResourceManager.GetString("AskForPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options {0} and {1} cannot be used together..
        /// </summary>
        internal static string ExclusiveOptions {
            get {
                return ResourceManager.GetString("ExclusiveOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feed is unchanged. Not writing..
        /// </summary>
        internal static string FeedUnchanged {
            get {
                return ResourceManager.GetString("FeedUnchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid release date. Use the format {0} or '{1}'..
        /// </summary>
        internal static string InvalidReleaseDate {
            get {
                return ResourceManager.GetString("InvalidReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program comes with ABSOLUTELY NO WARRANTY, to the extent permitted by law.
        ///You may redistribute copies of this program under the terms of the GNU Lesser General Public License..
        /// </summary>
        internal static string LicenseInfo {
            get {
                return ResourceManager.GetString("LicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing arguments. Try {0}.
        /// </summary>
        internal static string MissingArguments {
            get {
                return ResourceManager.GetString("MissingArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text editor found. Try setting the {0} environment variable..
        /// </summary>
        internal static string NoEditorFound {
            get {
                return ResourceManager.GetString("NoEditorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find any matching feed files..
        /// </summary>
        internal static string NoFeedFilesFound {
            get {
                return ResourceManager.GetString("NoFeedFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add additional manifest digests using the algorithm {ALG}..
        /// </summary>
        internal static string OptionAddDigest {
            get {
                return ResourceManager.GetString("OptionAddDigest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the implementations in {FEED} to this feed, putting them in the most sensible group..
        /// </summary>
        internal static string OptionAddFrom {
            get {
                return ResourceManager.GetString("OptionAddFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download missing archives, calculate manifest digests, etc...
        /// </summary>
        internal static string OptionAddMissing {
            get {
                return ResourceManager.GetString("OptionAddMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new implementation with the version number {VERSION}..
        /// </summary>
        internal static string OptionAddVersion {
            get {
                return ResourceManager.GetString("OptionAddVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only use the subdirectory {DIR} of the archive..
        /// </summary>
        internal static string OptionArchiveExtract {
            get {
                return ResourceManager.GetString("OptionArchiveExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {FILE} as the local copy of the archive..
        /// </summary>
        internal static string OptionArchiveFile {
            get {
                return ResourceManager.GetString("OptionArchiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an archive that can be downloaded from {URL} to an implementation..
        /// </summary>
        internal static string OptionArchiveUrl {
            get {
                return ResourceManager.GetString("OptionArchiveUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine all specified feeds into a single catalog {FILE}..
        /// </summary>
        internal static string OptionCatalog {
            get {
                return ResourceManager.GetString("OptionCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the feed file if it does not exist yet, without prompting..
        /// </summary>
        internal static string OptionCreate {
            get {
                return ResourceManager.GetString("OptionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the feed with the text editor specified by the {EDITOR} environment variable..
        /// </summary>
        internal static string OptionEdit {
            get {
                return ResourceManager.GetString("OptionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {PASS} to unlock the GnuPG secret key..
        /// </summary>
        internal static string OptionGnuPGPassphrase {
            get {
                return ResourceManager.GetString("OptionGnuPGPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the built-in help text..
        /// </summary>
        internal static string OptionHelp {
            get {
                return ResourceManager.GetString("OptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key to use for signing (if you have more than one, or if you want to resign with a different key)..
        /// </summary>
        internal static string OptionKey {
            get {
                return ResourceManager.GetString("OptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the algorithm {ALG} for manifest digests of newly added archives. May be specified multiple times..
        /// </summary>
        internal static string OptionManifestAlgorithm {
            get {
                return ResourceManager.GetString("OptionManifestAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option can only be used together with {0}..
        /// </summary>
        internal static string OptionRequires {
            get {
                return ResourceManager.GetString("OptionRequires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the --set-* options to the implementations with the version number {VERSION}..
        /// </summary>
        internal static string OptionSelectVersion {
            get {
                return ResourceManager.GetString("OptionSelectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the architecture to {ARCH} (in the form os-cpu)..
        /// </summary>
        internal static string OptionSetArch {
            get {
                return ResourceManager.GetString("OptionSetArch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the implementation ID to {DIGEST}..
        /// </summary>
        internal static string OptionSetID {
            get {
                return ResourceManager.GetString("OptionSetID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the canonical feed {URI}..
        /// </summary>
        internal static string OptionSetInterfaceUri {
            get {
                return ResourceManager.GetString("OptionSetInterfaceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the main executable to {EXEC}..
        /// </summary>
        internal static string OptionSetMain {
            get {
                return ResourceManager.GetString("OptionSetMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the release date to {DATE}. Use the format YYYY-MM-DD or 'today'. Leave empty to remove the date..
        /// </summary>
        internal static string OptionSetReleased {
            get {
                return ResourceManager.GetString("OptionSetReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the stability rating to {STABILITY}..
        /// </summary>
        internal static string OptionSetStability {
            get {
                return ResourceManager.GetString("OptionSetStability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the version number to {VERSION}..
        /// </summary>
        internal static string OptionSetVersion {
            get {
                return ResourceManager.GetString("OptionSetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark the latest testing implementation as stable..
        /// </summary>
        internal static string OptionStable {
            get {
                return ResourceManager.GetString("OptionStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More verbose output. Use twice for even more verbose output..
        /// </summary>
        internal static string OptionVerbose {
            get {
                return ResourceManager.GetString("OptionVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove any existing signatures..
        /// </summary>
        internal static string OptionUnsign {
            get {
                return ResourceManager.GetString("OptionUnsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display version information..
        /// </summary>
        internal static string OptionVersion {
            get {
                return ResourceManager.GetString("OptionVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an XML signature block. (All remote feeds must be signed.).
        /// </summary>
        internal static string OptionXmlSign {
            get {
                return ResourceManager.GetString("OptionXmlSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported values: {0}.
        /// </summary>
        internal static string SupportedValues {
            get {
                return ResourceManager.GetString("SupportedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
